---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-monitor-setup

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: storage-monitor-setup
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 12Gi
    requests.nvidia.com/gpu: 0
    requests.storage: "40Gi"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: storage-monitor-setup
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "2"
    defaultRequest:
      memory: 256Mi
      cpu: "1"
    type: Container

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-admin
  namespace: storage-monitor-setup

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-admin-secret
  namespace: storage-monitor-setup
  annotations:
    kubernetes.io/service-account.name: storage-admin
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storage-role
  namespace: storage-monitor-setup
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-rolebinding
  namespace: storage-monitor-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: storage-role
subjects:
- namespace: storage-monitor-setup
  kind: ServiceAccount
  name: storage-admin
